// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vermaat.Crm.Specflow.Sample
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("ContactTests", Description="Some tests specific to the contact entity. \r\nUsed to show tests that use unusual " +
        "fields like the address and composite fields", SourceFile="ContactTests.feature", SourceLine=0)]
    public partial class ContactTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ContactTests.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ContactTests", "Some tests specific to the contact entity. \r\nUsed to show tests that use unusual " +
                    "fields like the address and composite fields", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Basic contact test", new string[] {
                "API",
                "Chrome",
                "Cleanup"}, SourceLine=5)]
        public virtual void BasicContactTest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Basic contact test", null, new string[] {
                        "API",
                        "Chrome",
                        "Cleanup"});
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table33.AddRow(new string[] {
                        "First Name",
                        "John"});
            table33.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table33.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
#line 7
testRunner.Given("a contact named TestContact with the following values", ((string)(null)), table33, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table34.AddRow(new string[] {
                        "First Name",
                        "Jerry"});
            table34.AddRow(new string[] {
                        "Job Title",
                        "Chief Lazyness Officer"});
#line 12
testRunner.When("TestContact is updated with the following values", ((string)(null)), table34, "When ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table35.AddRow(new string[] {
                        "First Name",
                        "Jerry"});
            table35.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table35.AddRow(new string[] {
                        "Job Title",
                        "Chief Lazyness Officer"});
#line 16
testRunner.Then("TestContact has the following values", ((string)(null)), table35, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Lookup with multiple results tests", new string[] {
                "Chrome",
                "Cleanup"}, SourceLine=22)]
        public virtual void LookupWithMultipleResultsTests()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Lookup with multiple results tests", null, new string[] {
                        "Chrome",
                        "Cleanup"});
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table36.AddRow(new string[] {
                        "Account Name",
                        "DynamicHands"});
            table36.AddRow(new string[] {
                        "Main Phone",
                        "0612345678"});
            table36.AddRow(new string[] {
                        "Website",
                        "https://dynamichands.nl"});
            table36.AddRow(new string[] {
                        "Industry",
                        "Consulting"});
#line 24
testRunner.Given("an account named FirstAccount with the following values", ((string)(null)), table36, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table37.AddRow(new string[] {
                        "Account Name",
                        "DynamicHands"});
            table37.AddRow(new string[] {
                        "Main Phone",
                        "0612345678"});
            table37.AddRow(new string[] {
                        "Website",
                        "https://dynamichands.nl"});
            table37.AddRow(new string[] {
                        "Industry",
                        "Consulting"});
#line 30
testRunner.And("an account named SecondAccount with the following values", ((string)(null)), table37, "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table38.AddRow(new string[] {
                        "First Name",
                        "Jerry"});
            table38.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table38.AddRow(new string[] {
                        "Company Name",
                        "SecondAccount"});
            table38.AddRow(new string[] {
                        "Email",
                        "someone@test.com"});
#line 36
testRunner.When("a contact named TestLookup is created with the following values", ((string)(null)), table38, "When ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table39.AddRow(new string[] {
                        "First Name",
                        "Jerry"});
            table39.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table39.AddRow(new string[] {
                        "Company Name",
                        "SecondAccount"});
            table39.AddRow(new string[] {
                        "Email",
                        "someone@test.com"});
#line 42
testRunner.Then("TestLookup has the following values", ((string)(null)), table39, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check required of form items", new string[] {
                "Chrome",
                "Cleanup"}, SourceLine=49)]
        public virtual void CheckRequiredOfFormItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check required of form items", null, new string[] {
                        "Chrome",
                        "Cleanup"});
#line 50
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table40.AddRow(new string[] {
                        "First Name",
                        "John"});
            table40.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table40.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
#line 51
testRunner.Given("a contact named TestContact with the following values", ((string)(null)), table40, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "State"});
            table41.AddRow(new string[] {
                        "First Name",
                        "Recommended"});
            table41.AddRow(new string[] {
                        "Last Name",
                        "Required"});
            table41.AddRow(new string[] {
                        "Job Title",
                        "Optional"});
#line 56
testRunner.Then("TestContact\'s form has the following form state", ((string)(null)), table41, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check locked state of form items", new string[] {
                "Chrome",
                "Cleanup"}, SourceLine=62)]
        public virtual void CheckLockedStateOfFormItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check locked state of form items", null, new string[] {
                        "Chrome",
                        "Cleanup"});
#line 63
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table42.AddRow(new string[] {
                        "First Name",
                        "John"});
            table42.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table42.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
#line 64
testRunner.Given("a contact named TestContact with the following values", ((string)(null)), table42, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "State"});
            table43.AddRow(new string[] {
                        "First Name",
                        "Unlocked"});
            table43.AddRow(new string[] {
                        "Last Date Included in Campaign",
                        "Locked"});
#line 69
testRunner.Then("TestContact\'s form has the following form state", ((string)(null)), table43, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check combined state of form items", new string[] {
                "Chrome",
                "Cleanup"}, SourceLine=74)]
        public virtual void CheckCombinedStateOfFormItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check combined state of form items", null, new string[] {
                        "Chrome",
                        "Cleanup"});
#line 75
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table44.AddRow(new string[] {
                        "First Name",
                        "John"});
            table44.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table44.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
#line 76
testRunner.Given("a contact named TestContact with the following values", ((string)(null)), table44, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "State"});
            table45.AddRow(new string[] {
                        "First Name",
                        "Recommended, Unlocked, Visible"});
            table45.AddRow(new string[] {
                        "Last Name",
                        "Required, Unlocked, Visible"});
            table45.AddRow(new string[] {
                        "Job Title",
                        "Optional, Unlocked, Visible"});
            table45.AddRow(new string[] {
                        "Last Date Included in Campaign",
                        "Locked, Optional, Visible"});
#line 81
testRunner.Then("TestContact\'s form has the following form state", ((string)(null)), table45, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Filling DateTime fields", new string[] {
                "Cleanup",
                "Chrome",
                "API"}, SourceLine=88)]
        public virtual void FillingDateTimeFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filling DateTime fields", null, new string[] {
                        "Cleanup",
                        "Chrome",
                        "API"});
#line 89
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table46.AddRow(new string[] {
                        "First Name",
                        "John"});
            table46.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table46.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
            table46.AddRow(new string[] {
                        "Birthday",
                        "20-05-1985"});
            table46.AddRow(new string[] {
                        "Anniversary",
                        "10-10-2010"});
#line 90
testRunner.Given("a contact named TestContact with the following values", ((string)(null)), table46, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table47.AddRow(new string[] {
                        "First Name",
                        "John"});
            table47.AddRow(new string[] {
                        "Last Name",
                        "Smith"});
            table47.AddRow(new string[] {
                        "Job Title",
                        "CLO"});
            table47.AddRow(new string[] {
                        "Birthday",
                        "20-05-1985"});
            table47.AddRow(new string[] {
                        "Anniversary",
                        "10-10-2010"});
#line 97
testRunner.Then("TestContact has the following values", ((string)(null)), table47, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
