// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vermaat.Crm.Specflow.Sample
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("DateTesting", SourceFile="DateTesting.feature", SourceLine=0)]
    public partial class DateTestingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DateTesting.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DateTesting", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Test all Date and Time formats", new string[] {
                "Cleanup",
                "API",
                "Chrome"}, SourceLine=5)]
        public virtual void TestAllDateAndTimeFormats()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test all Date and Time formats", null, new string[] {
                        "Cleanup",
                        "API",
                        "Chrome"});
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table65.AddRow(new string[] {
                        "Name",
                        "Testing Dates"});
            table65.AddRow(new string[] {
                        "Date Only",
                        "1-1-2010"});
            table65.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2010"});
            table65.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2010 10:00"});
            table65.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2010"});
            table65.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2010 10:00"});
#line 7
testRunner.Given("a mv_datetester named TestDateTime with the following values", ((string)(null)), table65, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table66.AddRow(new string[] {
                        "Date Only",
                        "1-1-2010"});
            table66.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2010"});
            table66.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2010 10:00"});
            table66.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2010"});
            table66.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2010 10:00"});
#line 15
testRunner.Then("TestDateTime has the following values", ((string)(null)), table66, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Test updating all Date and Time formats", new string[] {
                "Cleanup",
                "API",
                "Chrome"}, SourceLine=23)]
        public virtual void TestUpdatingAllDateAndTimeFormats()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test updating all Date and Time formats", null, new string[] {
                        "Cleanup",
                        "API",
                        "Chrome"});
#line 24
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table67.AddRow(new string[] {
                        "Name",
                        "Testing Dates"});
            table67.AddRow(new string[] {
                        "Date Only",
                        "1-1-2010"});
            table67.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2010"});
            table67.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2010 10:00"});
            table67.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2010"});
            table67.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2010 10:00"});
#line 25
testRunner.Given("a mv_datetester named TestDateTime with the following values", ((string)(null)), table67, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table68.AddRow(new string[] {
                        "Date Only",
                        "1-1-2011"});
            table68.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2011"});
            table68.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2011 10:00"});
            table68.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2011"});
            table68.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2011 10:00"});
#line 33
testRunner.When("TestDateTime is updated with the following values", ((string)(null)), table68, "When ");
#line hidden
            TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table69.AddRow(new string[] {
                        "Date Only",
                        "1-1-2011"});
            table69.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2011"});
            table69.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2011 10:00"});
            table69.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2011"});
            table69.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2011 10:00"});
#line 40
testRunner.Then("TestDateTime has the following values", ((string)(null)), table69, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Test clearing all Date and Time formats", new string[] {
                "Cleanup",
                "API",
                "Chrome"}, SourceLine=48)]
        public virtual void TestClearingAllDateAndTimeFormats()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test clearing all Date and Time formats", null, new string[] {
                        "Cleanup",
                        "API",
                        "Chrome"});
#line 49
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table70.AddRow(new string[] {
                        "Name",
                        "Testing Dates"});
            table70.AddRow(new string[] {
                        "Date Only",
                        "1-1-2010"});
            table70.AddRow(new string[] {
                        "User Local Date Only",
                        "1-1-2010"});
            table70.AddRow(new string[] {
                        "User Local Date Time",
                        "1-1-2010 10:00"});
            table70.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        "1-1-2010"});
            table70.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        "1-1-2010 10:00"});
#line 50
testRunner.Given("a mv_datetester named TestDateTime with the following values", ((string)(null)), table70, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table71.AddRow(new string[] {
                        "Date Only",
                        ""});
            table71.AddRow(new string[] {
                        "User Local Date Only",
                        ""});
            table71.AddRow(new string[] {
                        "User Local Date Time",
                        ""});
            table71.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        ""});
            table71.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        ""});
#line 58
testRunner.When("TestDateTime is updated with the following values", ((string)(null)), table71, "When ");
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table72.AddRow(new string[] {
                        "Date Only",
                        ""});
            table72.AddRow(new string[] {
                        "User Local Date Only",
                        ""});
            table72.AddRow(new string[] {
                        "User Local Date Time",
                        ""});
            table72.AddRow(new string[] {
                        "Time Zone Independent Date Only",
                        ""});
            table72.AddRow(new string[] {
                        "Time Zone Independent Date Time",
                        ""});
#line 65
testRunner.Then("TestDateTime has the following values", ((string)(null)), table72, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
